import './style.css';
import { experiments, futureIdeas, rubric, comparisonPlan } from './content/experiments.js';
import { availableRuns, filterRuns, axisOptions, parseRoute, experimentHref, safeRuntimePath, escapeHtml as e, editorialScore } from './lab.js';
const main = document.querySelector('main');
let controller, currentRoute, currentExperiment, loadedRuntime, renderCount = 0;
const axisLabels = { model: 'Model', effort: 'Reasoning effort', promptApproach: 'Prompt approach' };
const arrow = '<span aria-hidden="true">↗</span>';
const art = '<div class="orbit-art" role="img" aria-label="An abstract planetary system"><div class="art-grid"></div><span class="art-cross cross-one">+</span><span class="art-cross cross-two">+</span><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="art-sun"></div><div class="art-planet planet-one"></div><div class="art-planet planet-two"><i></i></div><div class="art-planet planet-three"></div><div class="art-planet planet-four"></div><span class="art-label label-one">FIG. 01 / SMALL WORLDS</span><span class="art-label label-two">A LITTLE UNIVERSE<br>OF POSSIBILITIES</span><span class="art-spark">✳</span></div>';

function home() {
 const exp=experiments[0], runs=availableRuns(exp), controlled=runs.filter(r=>r.kind==='controlled').length;
 return `<section class="hero"><div><p class="eyebrow"><span class="short-rule"></span> AN AI FIELD JOURNAL</p><h1>Curiosity in.<br><em>Possibility out.</em><span class="hero-asterisk" aria-hidden="true">✳</span></h1><p class="hero-description">An idea, a prompt, a small leap into the unknown.<br>Exploring what AI can make, one experiment at a time.</p><a class="text-link" href="${experimentHref(exp.id)}">Explore the first experiment ↘</a></div><aside class="hero-note"><span class="note-star" aria-hidden="true">✧</span><p>Less “what if.”<br>More “let’s find out.”</p><span>PLAYABLE IDEAS.<br>VISIBLE PROCESS.</span></aside></section>
 <section><div class="section-label"><h2>From the notebook</h2><span>01 PUBLISHED EXPERIMENT</span></div><a class="feature-card" href="${experimentHref(exp.id)}"><div class="feature-art">${art}<span class="art-pill"><i></i> OPEN THE PLAYGROUND</span></div><div class="feature-copy"><div class="card-meta"><span>EXPERIMENT 001</span><span class="status-tag">IN PROGRESS</span></div><span class="category">INTERACTIVE 3D / CREATIVE CODING</span><h2>${e(exp.title)}</h2><p>A planetary playground. Three models. Four prompt approaches. A closer look at how a single idea can take different shapes.</p><div class="feature-bottom"><span>${runs.length} playable ${runs.length===1?'creation':'creations'}<i>·</i>${controlled}/24 comparison runs</span><span class="circle-arrow">↗</span></div></div></a></section>
 <section class="ideas-section"><div class="section-label"><h2>On the horizon</h2><span>IDEAS, NOT PROMISES</span></div><div class="idea-grid">${futureIdeas.map(idea=>`<article class="idea-card"><div class="idea-visual ${idea.visual}" aria-hidden="true">${'<i></i>'.repeat(11)}<span>SKETCH ${idea.number}</span></div><div class="idea-copy"><p class="eyebrow">${e(idea.category)}</p><h3>${e(idea.title)}</h3><p>${e(idea.description)}</p><span class="pencilled">PENCILED IN ↳</span></div></article>`).join('')}</div></section>
 <section class="manifesto-strip"><span class="manifesto-mark">↳</span><div><h2>The interesting part is the process.</h2><p>Every creation has a trail: the prompt, the setup, what worked, and what still needs a closer look.</p></div><a class="text-link" href="#/method">How this works ${arrow}</a></section><section class="journal-stats" aria-label="Journal statistics"><div><strong>01</strong><span>IDEAS EXPLORED</span></div><div><strong>${String(runs.length).padStart(2,'0')}</strong><span>PLAYABLE CREATIONS</span></div><div><strong>${String(runs.filter(r=>editorialScore(r.evaluation)).length).padStart(2,'0')}</strong><span>EDITORIAL REVIEWS</span></div><p>Small experiments.<br>Room to be surprised.</p></section>`;
}

function method() {
 return `<article class="method-page"><a class="back-link" href="#/">← Back to the journal</a><header class="article-header"><p class="eyebrow">A FEW GROUND RULES</p><h1>Show the work.<br><em>Keep the wonder.</em></h1><p class="article-deck">The artifacts are playable, the prompts are visible, and a missing result stays a missing result.</p></header><div class="method-grid"><section><span class="method-number">01</span><h2>One idea, different approaches</h2><p>Each post begins with an idea and a shared feature contract. We compare how model, reasoning effort, and prompt approach change the outcome.</p><p>Minimal and detailed alter specificity; bold and refined alter aesthetic direction. These are creative conditions, not perfectly isolated scientific variables.</p></section><section><span class="method-number">02</span><h2>Real runs, exact prompts</h2><p>Controlled runs record the actual model identifier, reasoning setting, and full user-level generation prompt, including public harness constraints.</p><p>Pocket Cosmos is a separate, assistant-curated baseline. Its original user request is available; its complete generation prompt, model, and effort are not.</p></section><section><span class="method-number">03</span><h2>Evidence before numbers</h2><p>Functional checks, implementation reviews, and rendered editorial judgments are different evidence. A passing math test doesn’t prove a button works.</p><p>Provisional implementation scores assess code, not visual quality. Editorial design scores require rendered review. Each score names its reviewer and evidence. Unreviewed work stays unscored.</p></section><section><span class="method-number">04</span><h2>Play, without a new bill</h2><p>The viewer switches prebuilt artifacts. It never generates a creation or calls a model. Each creation runs in a script-only sandbox with no access to the journal or its storage.</p><p>Assets are bundled and network connections blocked. Switching a creation or pressing Restart resets its simulation.</p></section></div><section class="rubric-section"><div class="section-label"><h2>The editorial rubric</h2><span>5 CRITERIA · 0–4 EACH</span></div><div class="rubric-list">${rubric.map((item,i)=>`<div><span>0${i+1}</span><h3>${e(item.name)}</h3><p>${e(item.description)}</p></div>`).join('')}</div><p class="rubric-note">0 absent / 1 weak / 2 adequate / 3 strong / 4 exceptional. These are assessments of individual artifacts, not universal model rankings.</p></section><section class="method-disclaimer"><h2>What this won’t tell you</h2><p>One output per condition cannot establish that a model is generally better. Prompt differences, run-to-run variation, implementation choices, and taste all matter. This is an open-ended field journal, not a benchmark leaderboard.</p></section><a class="solid-button" href="${experimentHref('planetary')}">Explore the planetary experiment ${arrow}</a></article>`;
}

function matrix(exp) {
 const runs=availableRuns(exp).filter(r=>r.kind==='controlled');
 return `<section class="comparison-section"><div class="section-label"><h2>The comparison, at a glance</h2><span>${runs.length} OF 24 RUNS AVAILABLE</span></div><p class="section-intro">Three models × two reasoning settings × four prompt approaches. Each cell is a separate creation. Pending cells become playable only when a real artifact is added.</p><div class="matrix-scroll" tabindex="0" aria-label="Comparison matrix; scroll horizontally on small screens"><table class="comparison-table"><caption class="sr-only">24 planned generation conditions</caption><thead><tr><th scope="col">MODEL / EFFORT</th>${comparisonPlan.approaches.map(a=>`<th scope="col">${a}</th>`).join('')}</tr></thead><tbody>${comparisonPlan.models.flatMap(model=>model.efforts.map(effort=>`<tr><th scope="row"><strong>${model.label}</strong><span>${effort}</span></th>${comparisonPlan.approaches.map(approach=>{const run=runs.find(r=>r.axes.model===model.label&&r.axes.effort===effort&&r.axes.promptApproach===approach);return `<td>${run?`<a class="matrix-run" href="${experimentHref(exp.id,run.id)}" aria-label="Open ${model.label}, ${effort}, ${approach}"><span><i></i> Play run</span><small>${run.evaluation?.implementation?'Code review available':editorialScore(run.evaluation)?'Editorial review available':'Unscored'}</small></a>`:'<span class="matrix-pending"><span>○</span> Pending</span>'}</td>`}).join('')}</tr>`)).join('')}</tbody></table></div><p class="matrix-note">Luna uses medium / max; Sol 6.1 and Astra use medium / xhigh. The original baseline sits outside this matrix. Selecting a cell never generates a new result.</p></section>`;
}

function experimentPage(exp) {
 return `<article class="experiment-page"><a class="back-link" href="#/">← Back to the journal</a><header class="article-header experiment-header"><div class="card-meta"><span>FIELD NOTE ${exp.number} <b>/</b> INTERACTIVE 3D</span><span class="status-tag">IN PROGRESS</span></div><h1>${e(exp.title)}<span class="article-star">✳</span></h1><p class="article-deck">${e(exp.subtitle)} A playful study of what changes when the model, the reasoning, or the way we ask changes.</p><div class="article-tags">${exp.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div></header><section class="experiment-prologue"><div><p class="eyebrow">THE QUESTION</p><h2>${e(exp.question)}</h2></div><div><p>The first seed was Pocket Cosmos: five fictional planets, a small sun, and a comet you can send flying. A starting point, with its own charm and its own unknowns.</p><p>Now the same broad idea is becoming a set of controlled creations. Explore the artifacts, inspect the exact prompts, and check the evidence before drawing conclusions.</p></div></section><section class="workbench"><div class="section-label"><h2>The playground</h2><span>PREBUILT CREATIONS / LIVE IN YOUR BROWSER</span></div><div id="picker"></div><div id="viewer-container"></div><div id="run-record"></div></section>${matrix(exp)}<section class="field-notes"><div><p class="eyebrow">NOTES FROM THE BENCH</p><h2>A beginning,<br><em>not a verdict.</em></h2></div><div><p>The baseline is intentionally playful: circular orbits, invented worlds, and a comet on a designed path. It is a rendering experiment, not an astronomy or gravity simulator.</p><p>A meaningful comparison needs more than a good-looking screenshot. Here, the artifact, inputs, test evidence, and assessment live together. Missing evidence remains visible.</p><a class="text-link" href="#/method">Read the full method ${arrow}</a></div></section></article>`;
}

function picker(exp,route) {
 const runs=availableRuns(exp), filtered=filterRuns(runs,route.filters), requested=runs.find(r=>r.id===route.variant), selected=requested&&filtered.includes(requested)?requested:filtered[0];
 document.querySelector('#picker').innerHTML=`<div class="filter-bar">${Object.entries(axisLabels).map(([axis,label])=>`<label><span>${label}</span><select data-axis="${axis}" aria-label="Filter by ${label.toLowerCase()}"><option value="">All ${axis==='model'?'models':axis==='effort'?'efforts':'approaches'}</option>${axisOptions(runs,axis,route.filters).map(o=>`<option value="${e(o.value)}" ${route.filters[axis]===o.value?'selected':''} ${!o.available?'disabled':''}>${e(o.value)}${!o.available?' · no match':''}</option>`).join('')}</select></label>`).join('')}<button class="clear-filters" id="clear-filters" ${Object.values(route.filters).some(Boolean)?'':'disabled'}>Clear filters ↺</button></div><div class="run-choices-heading"><span>${filtered.length} MATCHING ${filtered.length===1?'CREATION':'CREATIONS'}</span><span>SELECT TO SWITCH</span></div>${route.variant&&!requested?'<p class="notice" role="status">That variant isn’t available. Showing an available creation instead.</p>':''}<div class="run-choices" aria-label="Choose a creation">${filtered.map(run=>`<button class="run-choice ${selected?.id===run.id?'selected':''}" data-run="${e(run.id)}" aria-pressed="${selected?.id===run.id}"><span class="run-choice-dot"></span><span><strong>${e(run.title)}</strong><small>${run.kind==='baseline'?'Original demo · provenance incomplete':`${e(run.axes.model)} / ${e(run.axes.effort)} / ${e(run.axes.promptApproach)}`}</small></span><span class="run-choice-score">${run.evaluation?.implementation?'Code review':editorialScore(run.evaluation)?'Reviewed':'Unscored'}</span></button>`).join('')||'<div class="empty-state"><h3>No creation matches these filters.</h3><p>Clear the filters or try another combination. Missing results aren’t silently substituted.</p><button class="solid-button" id="empty-clear">Clear filters</button></div>'}</div>`;
 document.querySelectorAll('[data-axis]').forEach(select=>select.addEventListener('change',()=>{const filters={...route.filters,[select.dataset.axis]:select.value}, matches=filterRuns(runs,filters);location.hash=experimentHref(exp.id,matches.find(r=>r.id===selected?.id)?.id||matches[0]?.id,filters)}));
 const clear=()=>{location.hash=experimentHref(exp.id,selected?.id)};
 document.querySelector('#clear-filters').onclick=clear;document.querySelector('#empty-clear')?.addEventListener('click',clear);
 document.querySelectorAll('[data-run]').forEach(b=>b.addEventListener('click',()=>{location.hash=experimentHref(exp.id,b.dataset.run,route.filters)}));
 if(selected){record(selected);if(loadedRuntime!==selected.id)viewer(selected)}else{controller?.abort();loadedRuntime=null;document.querySelector('#viewer-container').innerHTML='';document.querySelector('#run-record').innerHTML=''}
}

function implementationHtml(record) {
 if(!record?.scores?.length)return '';
 const scores=record.scores, valid=scores.every(s=>Number.isFinite(s.value)&&s.value>=0&&s.value<=4);
 return `<section class="implementation-review"><h4>Provisional implementation score</h4><p class="implementation-total">${valid?`${scores.reduce((n,s)=>n+s.value,0)} / ${scores.length*4}`:'Not scored'}</p><p>${e(record.method||'Code review; rendered visuals not rated.')}</p><small>${e(record.reviewer||'Reviewer not recorded')} · ${e(record.evaluatedAt||'Date not recorded')}</small><ul>${scores.map(s=>`<li><div><strong>${e(s.label||s.id)}</strong><p>${e(s.evidence)}</p></div><span>${valid?`${s.value}/4`:'—'}</span></li>`).join('')}</ul></section>`;
}

function record(run) {
 const ev=run.evaluation||{},fun=ev.functional,score=editorialScore(ev),prompt=run.prompt;
 document.querySelector('#run-record').innerHTML=`<div class="run-record-grid"><section class="record-panel"><div class="record-heading"><h3>The prompt</h3><span class="small-badge ${prompt?.status==='complete'?'complete':''}">${prompt?.status==='complete'?'FULL RECORD':'PARTIAL RECORD'}</span></div><p class="record-intro">${e(prompt?.note||'The generation prompt has not been recorded.')}</p>${(prompt?.messages||[]).map(m=>`<details class="prompt-disclosure" open><summary>${e(m.role==='user'?'Exact user prompt':m.role)} ${arrow}</summary><pre>${e(m.content)}</pre></details>`).join('')}<div class="provenance"><p class="eyebrow">PROVENANCE</p><strong>${e(run.provenance.label)}</strong><p>${e(run.provenance.note)}</p><dl><div><dt>Model identifier</dt><dd>${e(run.provenance.modelId||'Not recorded')}</dd></div><div><dt>Reasoning effort</dt><dd>${e(run.provenance.effort||'Not recorded')}</dd></div><div><dt>Prompt approach</dt><dd>${e(run.axes.promptApproach)}</dd></div></dl></div></section><section class="record-panel"><div class="record-heading"><h3>The evidence</h3><span class="small-badge">${score?'REVIEWED':'DESIGN UNSCORED'}</span></div><div class="evidence-summary"><div><span>EDITORIAL DESIGN</span><strong>${score?`${score.earned}<small>/${score.possible}</small>`:'—'}</strong><p>${score?`${e(ev.editorial.reviewer)} · ${e(ev.editorial.evaluatedAt)}`:'No rendered editorial rating yet'}</p></div><div><span>FUNCTIONAL CHECKS</span><strong>${Number.isInteger(fun?.passed)&&Number.isInteger(fun?.total)?`${fun.passed}<small>/${fun.total}</small>`:'—'}</strong><p>${e(fun?.scope||'Not yet tested')}</p></div></div><p class="evidence-note">${e(fun?.note||'Functional checks have not been recorded.')}</p><div class="browser-evidence"><span class="evidence-icon">${ev.browser?.status==='verified'?'✓':'○'}</span><div><strong>${ev.browser?.status==='verified'?'Browser checks recorded':'3D browser behavior not verified'}</strong><p>${e(ev.browser?.note||'No live browser evidence has been recorded.')}</p></div></div>${implementationHtml(ev.implementation)}<details class="score-details"><summary>Editorial rubric <span>0–4 per criterion</span></summary><ul>${rubric.map(item=>{const result=score&&ev.editorial.scores.find(s=>s.id===item.id);return `<li><div><strong>${e(item.name)}</strong><p>${e(result?.evidence||item.description)}</p></div><span>${result?`${result.value}/4`:'—'}</span></li>`}).join('')}</ul></details>${ev.measurements?.length?`<dl class="measurements">${ev.measurements.map(m=>`<div><dt>${e(m.label)}</dt><dd>${e(m.value)} ${e(m.unit||'')}</dd></div>`).join('')}</dl>`:''}${ev.notes?.length?`<ul class="evaluation-notes">${ev.notes.map(n=>`<li>${e(n)}</li>`).join('')}</ul>`:''}<a class="text-link" href="#/method">How the scoring works ${arrow}</a></section></div>`;
}

async function viewer(run) {
 controller?.abort();controller=new AbortController();const signal=controller.signal;loadedRuntime=run.id;document.body.classList.remove('viewer-expanded');
 const container=document.querySelector('#viewer-container');
 container.innerHTML=`<div class="runtime-shell"><div class="runtime-toolbar"><div><i class="runtime-indicator"></i><strong>${e(run.title)}</strong><span class="runtime-kind">${run.kind==='baseline'?'ORIGINAL BASELINE':'CONTROLLED RUN'}</span></div><div class="runtime-actions"><button id="restart-runtime" title="Restart this creation">↺ <span>Restart</span></button><button id="expand-runtime" aria-expanded="false">⤢ <span>Expand</span></button></div></div><div class="runtime-stage"><div class="runtime-loading" role="status"><span>✳</span><h3>Opening a little universe…</h3><p>Loading a prebuilt creation. No model call, no generation.</p></div></div><div class="runtime-caption"><span><i></i> ISOLATED PLAYGROUND</span><p>Interact inside the frame. Restart to begin again.</p></div></div>`;
 document.querySelector('#restart-runtime').onclick=()=>viewer(run);document.querySelector('#expand-runtime').onclick=()=>expand();
 try{if(!safeRuntimePath(run.runtime))throw Error('Invalid artifact path.');const response=await fetch(run.runtime,{signal,cache:'no-cache'});if(!response.ok)throw Error(`Artifact request failed (HTTP ${response.status}).`);const html=await response.text();if(!/<html[\s>]/i.test(html)||!html.includes('Content-Security-Policy'))throw Error('Artifact is not a valid isolated build.');if(signal.aborted||!container.isConnected)return;const frame=document.createElement('iframe');frame.title=`${run.title} interactive creation`;frame.setAttribute('sandbox','allow-scripts');frame.setAttribute('referrerpolicy','no-referrer');frame.setAttribute('allow',"camera 'none'; microphone 'none'; geolocation 'none'; payment 'none'; clipboard-read 'none'; clipboard-write 'none'");frame.addEventListener('load',()=>{if(!signal.aborted)document.querySelector('#announcement').textContent=`${run.title} document loaded. Rendering capabilities depend on your browser.`},{once:true});frame.srcdoc=html;container.querySelector('.runtime-stage').replaceChildren(frame)}catch(error){if(error.name==='AbortError'||signal.aborted||!container.isConnected)return;container.querySelector('.runtime-stage').innerHTML=`<div class="runtime-error" role="alert"><span>↺</span><h3>This creation couldn’t load.</h3><p>${e(error.message)}</p><button class="solid-button" id="retry-runtime">Try again</button></div>`;document.querySelector('#retry-runtime').onclick=()=>viewer(run)}
}
function expand(force){const shell=document.querySelector('.runtime-shell');if(!shell)return;const expanded=typeof force==='boolean'?force:!shell.classList.contains('expanded');shell.classList.toggle('expanded',expanded);document.body.classList.toggle('viewer-expanded',expanded);const b=document.querySelector('#expand-runtime');b.setAttribute('aria-expanded',String(expanded));b.innerHTML=expanded?'× <span>Close</span>':'⤢ <span>Expand</span>';if(!expanded)b.focus({preventScroll:true})}
function render(){const route=parseRoute(location.hash), previous=currentRoute;currentRoute=route;const exp=route.page==='experiment'?experiments.find(x=>x.id===route.id):null;document.querySelectorAll('[data-nav]').forEach(a=>{if((route.page==='method'?'method':'home')===a.dataset.nav)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(exp&&previous?.page==='experiment'&&currentExperiment?.id===exp.id){picker(exp,route);return}controller?.abort();loadedRuntime=null;currentExperiment=exp;document.body.classList.remove('viewer-expanded');if(route.page==='home'){document.title='Planet Lab · An AI field journal';main.innerHTML=home()}else if(route.page==='method'){document.title='The method · Planet Lab';main.innerHTML=method()}else if(exp){document.title=`${exp.title} · Planet Lab`;main.innerHTML=experimentPage(exp);picker(exp,route)}else{document.title='Page not found · Planet Lab';main.innerHTML='<section class="not-found"><p class="eyebrow">AN UNCHARTED CORNER</p><h1>Nothing orbiting here.</h1><p>This page doesn’t exist. The journal is a good place to start.</p><a class="solid-button" href="#/">Back to the journal ↗</a></section>'}window.scrollTo({top:0,behavior:'instant'});if(renderCount++)main.focus({preventScroll:true})}
window.addEventListener('hashchange',render);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('viewer-expanded'))expand(false)});document.querySelector('.skip-link').onclick=event=>{event.preventDefault();main.focus()};render();
